### ISSUE TITLE
Allow custom user agent

### ISSUE THREAD

**Issue by samwilson** [hamstar/Wikimate#103]
It would be good to be able to set a custom user agent, so that clients using this library can abide by the [User-Agent policy](https://meta.wikimedia.org/wiki/User-Agent_policy).

I suggest adding a new method: `Wikimate::setUserAgent( string $userAgent ): void`

**Comment by samwilson** [comment]
This is to help with https://phabricator.wikimedia.org/T286099

**Comment by Xymph** [comment]
We're just in the process of wrapping up v0.13.0, so I'll schedule this for the next release (it's a small easy addition).
Nice to see this little library in use at big Mediawiki. :)

**Comment by Xymph** [comment]
This is now resolved in `master`, and will be in the v0.14.0 release.
