### ISSUE TITLE
Warning:  Creating default object from empty value

### ISSUE THREAD

**Issue by samwilson** [hamstar/Wikimate#118]
I'm getting the following warning when trying to save a page in the Module namespace with `$wiki->getPage( 'Module:ExtensionJson' );`, with Wikimate 0.13.0:

```
PHP Warning:  Creating default object from empty value
              in extjsonuploader/vendor/hamstar/wikimate/Wikimate.php on line 678
PHP Stack trace:
PHP   1. {main}() extjsonuploader/run.php:0
PHP   2. MediaWiki\Tools\ExtensionJsonUploader\App->run() extjsonuploader/run.php:18
PHP   3. Wikimate->getPage() extjsonuploader/src/App.php:73
PHP   4. WikiPage->__construct() extjsonuploader/vendor/hamstar/wikimate/Wikimate.php:247
PHP   5. WikiPage->getText() extjsonuploader/vendor/hamstar/wikimate/Wikimate.php:505
```

It looks like `$this->sections` isn't being initialized before this is called;

```php
$this->sections->byIndex[0]['offset']      = 0;
```

**Comment by Xymph** [comment]
I'm aware of that, been like that for years, but I don't get a warning myself, not even with error_reporting = E_ALL, in PHP 5.6 nor 7.2. That makes it difficult to verify my intended fix is the correct one.
Can you provide more info why you'd be getting the warning?

**Comment by samwilson** [comment]
It's a change in PHP 7.4. See [this comparison](https://3v4l.org/n1aZc) of different versions. In PHP 8 it'll be a fatal error.

**Comment by Xymph** [comment]
Ok, if you need a stopgap, insert in the WikiPage constructor before the [getText line](https://github.com/hamstar/Wikimate/blob/b8798187992beedacc3cce28d2ff007c7d51ad94/Wikimate.php#L505):
`$this->sections = new stdClass();`
The formal fix will be in the next release.

Nifty site, btw.

**Comment by samwilson** [comment]
Thanks!
