### ISSUE TITLE
Captcha answer – the unknown answer

### ISSUE THREAD

**Issue by Dusan-Krehel** [hamstar/Wikimate#144]
I have a new wiki account with none changes. If I edit a page, so I have the error answer:
<pre>Error: Array
(
    [page] => Unexpected edit response: Failure
)</pre>

If i enable the debug, so I see the answer:
<pre>edit POST response:
Array
(
    [edit] => Array
        (
            [captcha] => Array
                (
                    [type] => image
                    [mime] => image/png
                    [id] => ID_ANONYMIZED
                    [url] => /w/index.php?title=Posebno:Captcha/image&wpCaptchaId=ID_ANONYMIZED
                )

            [result] => Failure
        )

)</pre>

The version: Wikimate-1.0.0.

**Comment by Xymph** [comment]
A captcha on an API naturally defeats the purpose of automatic, script-wise edits. I can't say more at this point, as the report lacks info about which wiki site and what captcha plugin is involved.

**Comment by Dusan-Krehel** [comment]
Wiki: hrwiki. (Un)more: https://hr.wikipedia.org/w/index.php?title=Posebno:Captcha/

Maybe, the human doesn't need a details. The user need maybe only the error "The captcha is in the way", none "Unknown error". The program only detect the key "captcha" in the API answer.

**Comment by Xymph** [comment]
I'm afraid I don't quite follow what you're writing, nor what you now expect from Wikimate.

**Comment by waldyrious** [comment]
If I'm reading @Dusan-Krehel's last comment correctly, one thing Wikimate could do is recognize a captcha-related error in an error response (by means of the presence of the `captcha` key) and provide a more informative error than "Unexpected edit response: Failure".

I don't know if that error response format is common to all captcha extensions, but the wording used in the [MediaWiki docs](https://www.mediawiki.org/wiki/Manual:Combating_spam#CAPTCHA) ("The ConfirmEdit extension for MediaWiki provides an extensible captcha framework") appears to suggest that other CAPTCHA extensions are expected to work with it. And indeed in the [Croatian Wikipedia's Special:Version](https://hr.wikipedia.org/wiki/Posebno:Verzija) page, it can be seen that both the ConfirmEdit and the FancyCaptcha extensions are installed — the latter being one of those [listed](https://www.mediawiki.org/wiki/Extension:ConfirmEdit#FancyCaptcha) as one of the captcha modules provided by ConfirmEdit.

**Comment by Dusan-Krehel** [comment]
@waldyrious waldyrious Yes.

No only hrwiki, but plwiki and srwiki.

Maybe, If the program is not sure, it can print at least a warning.

**Comment by Xymph** [comment]
Well, I finally had some time/inspiration to look into this, read up on the documentation, set up a captcha on my local wiki for testing, and implement a proper error message. See #145.
I tested a file upload too, but the captcha extension doesn't deny that.

Note that the default configuration doesn't deny API requests from [actual bot accounts](https://www.mediawiki.org/wiki/Extension:ConfirmEdit#Configuration), so @Dusan-Krehel this may be a route to pursue for making bot scripted updates on your local Wikipedia.
