### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by kendinciz** [hamstar/Wikimate#26]
I copied the code here (https://github.com/hamstar/Wikimate#usage). But I cant login. when ı start the page, it comes a empty page. screenshots:

code:
![2014-08-19 15 11 16](https://cloud.githubusercontent.com/assets/8396288/3965692/f2b50e2a-2799-11e4-8185-77db615b5df3.png)

empty page:
![2014-08-19 15 07 46](https://cloud.githubusercontent.com/assets/8396288/3965693/f2b58ba2-2799-11e4-934a-d23a732b4e4b.png)

**Comment by vlasvlasvlas** [comment]
hi, the same thing is happening to me..

**Comment by Xymph** [comment]
@waldyrious  No follow-up on these reports, and login works fine if correctly configured. Time to close this issue?

**Comment by waldyrious** [comment]
Agreed @Xymph. @kendinciz and @vlasvlasvlas, please comment if you believe this issue should be reopened.
