### ISSUE TITLE
Page without sections leaves length undefined

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#35]
Because ef19eec removed the `isset( $length )` test, a page without sections results in a PHP Notice on that `substr` statement, as the `length` fields in the section arrays are left undefined for the first/intro section.

Also, I found three more lowercase mentions of 'api' in the doxygen blocks, above Wikimate query and WikiPage getText (twice).
And the Wikimate constants SECTIONLIST_BY_* can be removed, those belong in class WikiPage only.

**Comment by waldyrious** [comment]
Looks good, I would just prefer the comment on 41a8e96 to be a tad more descriptive (i.e. explaining what that `if` condition means, and that we're creating a "virtual" section encompassing the whole page).
