### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by waldyrious** [hamstar/Wikimate#36]
As described in https://github.com/hamstar/Wikimate/pull/34#issuecomment-251193934

**Comment by Xymph** [comment]
Maybe this one can tag along here: `getAllSections` should have an `@exception` field in the comment block for the Exception it can throw.

Also, in README and USAGE the object creation and login call are wrapped in a try/catch block, but constructor and login method (nor the underlying `Request_Session` call) can't generate exceptions. This documentation may be left over from the old curl approach.
A simple `if` test on the `login()` result is all the user needs.

**Comment by Xymph** [comment]
Missed these while we worked on #32. :-\

Above `setText`, this description:
`@param   string   $section  The section to edit (null for whole page)`
should be something like:
`@param   mixed   $section  Section index to edit (whole page by default, "new" for new section)`

Above `setSection`:
`@param   mixed    $section  Section index, new by default`
should similarly be:
`@param   mixed    $section  Section index to edit (intro by default, "new" for new section)`

No need to mention what the default value is, as that is shown in the parameter list, but `@param` should describe its effect.

**Comment by Xymph** [comment]
More above `setText` and `setSection` as result of [this analysis](https://github.com/hamstar/Wikimate/issues/38#issuecomment-251515134), if no changes result from that ticket:
`@param   string   $summary  Summary text`
should be:
`@param   string   $summary  Summary text, and section header in case of new section`

The try/catch approach is still used in examples.php as well, updating that may be beyond the scope of this ticket.

**Comment by Xymph** [comment]
Note: the doxygen param changes proposed above were already incorporated in 8a011e6.

**Comment by waldyrious** [comment]
I intended to pick it up when I had the time, but if you want to, please go ahead :)

Btw, sorry if I'm not able to keep up with your pace. I hope it isn't discouraging -- in fact, I'm thinking I'll call upon @hamstar to considering making you a collaborator as well, so you won't have to face so many speed bumps to your enthusiastic and very welcome contributions :) I'll see if I can get hold of him.

**Comment by Xymph** [comment]
I figured I might be keeping you too busy with reviews and merges to be able to attend to this. :) But that's no problem, I have more than enough to do outside Wikimate, and don't experience the current situation as a speed bump. Besides, I'm running out of bugs to fix, so my pace will drop soon enough. ;)

Given my relative inexperience with Git(Hub) I don't like to have the additional responsibility of being a collaborator now. It's good that someone else reviews my issues and commits, and provides constructive feedback.

Meanwhile, I'll get going on (what's left of) this ticket then.

**Comment by waldyrious** [comment]
I understand, but allow me to insist, on the grounds that (1) collaborator status doesn't mean your changes go unreviewed, just that you won't be blocked if nobody's available; (2) it is not really a "status", with associated responsibilities and privileges, as much as it is a removal of barriers to contribution which are in place mostly as a protective measure for the integrity of the project -- kind of how autoconfirmed works on Wikipedia, after a few days and a number of contributions (and no block) demonstrates that the person is acting in good faith (which in your case, we've seen more than enough evidence of such); and (3) you will be able to review other's contribution, in the occasions that other collaborators are unavailable (how do you think I ended up being the de-facto maintainer for this project? ;))

In any case, I had already emailed Robert before seeing your comment (sorry about that), so the wheels are turning already. If you really insist on not remaining a collaborator, you can always remove your status yourself later on :)

**Comment by Xymph** [comment]
Alright, I'll try not to break anything if and when it's granted. :stuck_out_tongue_winking_eye: 

Btw, I updated the project's status [here](https://www.mediawiki.org/w/index.php?title=API:Client_code&diff=prev&oldid=2254918) as well.

**Comment by waldyrious** [comment]
For future reference, two of the three initial mentioned in the link from the opening comment on this thread were already fixed in commits included in PR #37:

- the constants in class Wikimate aren't used. Since that functionality exists (and belongs) in WikiPage, I think they should be removed from Wikimate -- fixed in 4395534

- three more lowercase mentions of 'api' in the doxygen blocks, above Wikimate query and WikiPage getText (twice) -- fixed in 1b6971c

**Comment by Xymph** [comment]
Also for future reference, the `setText/setSection` doxygen changes proposed in the above comments [here](https://github.com/hamstar/Wikimate/issues/36#issuecomment-251473275) and [here](https://github.com/hamstar/Wikimate/issues/36#issuecomment-251619896) were addressed/superseded in PR #45, commit 8d97ace.
