### ISSUE TITLE
newSection: effect of $name parameter is not consistent

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#38]
Discovered this while writing a script that uses this method (am I really the first? :)).
$name is passed onto $summary in the setSection call, and ends up as summary in the page's editing history. So it should be named $summary accordingly.

I considered the possibility that the intent really was to pass the section header, but that makes no sense. Then setSection or setText would have a $name parameter too, and somewhere the header and body would need to be combined, but for that the section depth (number of ='s) would also be needed. So no: $text needs to include everything the user wants to put into the section, including header (or not).

**Edit**: I may be mistaken, looking into it further.

**Comment by Xymph** [comment]
The pertaining MediaWiki API [edit parameters](https://www.mediawiki.org/wiki/API:Edit#Parameters) behave in a way I didn't expect:

If `section=new` and `sectiontitle` is undefined (as it is in Wikimate) then `summary` is used as new section header with a fixed level of 2 (wrapped in '=='). Additionally, `summary` is embedded in a standardized edit summary, `/* summary */ new section`, which is then rendered in the page history as usual: _→summary: new section_ (with hyperlinked arrow to the section anchor, and greyed section name).

In contrast, when editing an existing section, `summary` is used verbatim. But if a new section is created and the `sectiontitle` parameter **is** included (edited my local WikiPage to test that), then `summary` is used verbatim in the history too!
I find this rather counter-intuitive, but I guess the API designers had a good reason for it.

Anyway, `newSection`'s `$name` parameter is therefore correctly named as it currently stands.

We could debate whether to add a `sectiontitle` parameter to `newSection`, but that would then also need to be passed through `setSection` and `setText`. This would grant the user more control over the summaries in a page history (in the bot scripts I'm writing I'd like to flag them as "Automated edits"), but change the parameter list of multiple methods. Maybe that's not worth it for new sections, which seems to me is a task far less common for bots than text and section edits. What do you think, @waldyrious ?

**Comment by waldyrious** [comment]
I see. This behavior reflects what the actual mediawiki UI does: when creating a new section (which normally only happens in discussion pages), you don't get a summary field, only a "subject" field above the edit box, which becomes the title of the section, and part of the automatic edit summary, as you describe.

> then `summary` is used verbatim in the history too! I find this rather counter-intuitive

Did you mean to say that `sectiontitle` is used in the history as the edit summary? Otherwise I'm not sure I understand why using `summary` as the edit summary (i.e. in the history) is counter-intuitive.

**Comment by Xymph** [comment]
Ah of course, hadn't realized it was the same behavior.

> Otherwise I'm not sure I understand why using `summary` as the edit summary (i.e. in the history) is counter-intuitive.

I meant that `summary` is used either verbatim or in a preformatted string, depending on _two_ other conditions: new or existing section, and presence/absence of `sectiontitle`. That's not really transparent use of a parameter.

But at this time I can live with it, the preformatted string is fine, and I don't need to create new sections via bot scripts for now anyway.
Also, since one of Wikimate's primary goals is to be simple and easy to use, with straightforward documentation (unlike something like [Apibot](http://apibot.zavinagi.org/)), I think we should leave the pertaining methods as is.

**Comment by waldyrious** [comment]
Ok then. I'll rename the issue to reflect the current understanding. Feel free to close it if you believe keeping the current behavior is preferred. I did consider that we could attempt to provide a more predictable interface (i.e. internally translate the parameters into the appropriate API parameters, even if the actual names don't match), but I'm not sure doing something different than mediawiki would be advisable.

**Comment by Xymph** [comment]
I don't think that's wise either. Issue closed.
