### ISSUE TITLE
setSection/setText: allow specifying section by name

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#40]
Having written a few bot scripts using Wikimate by now, this experience leads to yet another issue (btw, how can issues be labeled as Bug, Feature request, etc?).

One can obtain a section's content via its name using `getSection`, but MediaWiki API requires its index when updating it, and Wikimate passes that requirement right on to the user. This means in most scripts one has to add extra code to compute the index number from the section name.

I would like to see this functionality added to `setText` (and thus `setSection`) so that user code can be simplified.

**Comment by waldyrious** [comment]
> btw, how can issues be labeled as Bug, Feature request, etc?

You have to be a collaborator in the repo to label issues. Unfortunately I can't grant you that status, so it will depend on @hamstar's reaction.

**Comment by Xymph** [comment]
> #36: In any case, I had already emailed Robert before seeing your comment (sorry about that), so the wheels are turning already.

I take it they have come to a grinding halt? :wink: So maybe you can assign labels to recent issues, say from #26 onwards?

**Comment by waldyrious** [comment]
I've pinged him again. He had answered and was keen on giving you collaborator status, but it must have slipped his mind (understandable since he hasn't been around github for a while now).

**Comment by Xymph** [comment]
> So maybe you can assign labels to recent issues, say from #26 onwards?

I did that now. :sunglasses:

**Comment by waldyrious** [comment]
Woohoo! 🎉
