### ISSUE TITLE
WikiPage methods: visibility should be declared

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#44]
[Per coding guidelines](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#43-methods). Same for the Wikimate constructor (all its other methods already have declarations).

Also, class & method opening braces could go on separate lines.

**Comment by waldyrious** [comment]
Oh interesting. I wonder if the auto-closing trick only works if the message is in the actual commit messages, not the PR title? Something to investigate further :)

**Comment by Xymph** [comment]
Wondered about this too, that might well be the requirement.
