### ISSUE TITLE
Add subsections optionally to getSection result

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#53]
`setSection/setText` write the specified section contents with the provided text as is. MediaWiki API uses that text to replace the entire section, including any subsections. But WikiPage discards any nesting structure in the page, and `getSection` only returns the initial portion of a section, not its subsections. That's convenient when the initial section is all one wants to change, but there's no convenient way to write that back without discarding its subsection(s).

I don't think `setSection/setText` should be changed as they follow the API mechanism. And sometimes one _does_ want to discard all subsections (as has been the case in a previous bot script I wrote) or the user already knows to be working on a subsection that has no further subsections.

Instead I propose to add a new method `getSubsections($section)` so that the user can do something like this:
```
$oldsection = getSection(1); // or 'name'
$newsection = transform($oldsection);
$newsection .= getSubsections(1); // or 'name'
setSection($newsection);
```
This also will require adding a field to the two `$this->sections` arrays to keep track of the nesting level or depth, i.e. the number of `=`'s of each header.

Comments (@waldyrious)?

**Comment by waldyrious** [comment]
> I don't think `setSection/setText` should be changed as they follow the API mechanism.

I don't understand why you think the API's behavior is less intuitive than Wikimate's. At first analysis I'm inclined to think otherwise. Could you expand a bit on your reasoning?

**Comment by Xymph** [comment]
It's not a matter of intuitiveness but of difference in section model: MediaWiki's is hierarchical, WikiPage's is flat. For example [this page](https://doomwiki.org/wiki/Item) parses into [these sections](https://doomwiki.org/w/api.php?action=parse&page=Item&contentmodel=wikitext&prop=sections), so fetching [section 10](https://doomwiki.org/w/api.php?action=query&format=xmlfm&titles=Item&prop=info|revisions&rvprop=content&rvsection=10)  (with the rvsection parameter) includes all its (nested) subsections. Section [11](https://doomwiki.org/w/api.php?action=query&format=xmlfm&titles=Item&prop=info|revisions&rvprop=content&rvsection=11), [12](https://doomwiki.org/w/api.php?action=query&format=xmlfm&titles=Item&prop=info|revisions&rvprop=content&rvsection=12), you get the picture.

On the WikiPage side, `getSection(10, true)` returns only "==Other games==" with empty body, 11 only the "===[[Heretic]]===" header, and 12 &ndash; finally &ndash; the same as MW. This happens because `getText` performs its own section splitting from the `preg_match_all` statement down. It keeps only one copy of the entire page content in the object (which is a good thing), and each computed length goes until the next section header of any level, not of the same level.

The net effect is that getSection doesn't provide in its entirety what setSection requires to rewrite a section of which the preamble part (before the first subsection header) has been changed, without the undesirable side effect of discarding any subsections. Hence my proposal to add a method that provides that additional content to the user. This doesn't change how existing methods operate.

I am of course not sure why getSection (and WikiPage as a whole) uses this flat section model that doesn't mimic MediaWiki's, but perhaps because this whole project is intended to provide easy and simple API access. It would be interesting to know @hamstar's reasoning behind designing WikiPage this way.

So, as alternative to my proposed new method, `getText`'s section processing could be changed to match MW's model, but that would break compatibility in the `getSection` method. Unless it's done with an additional parameter that defaults to the old behavior, but in both cases changes to the underlying `$this->sections` arrays are needed,

**Comment by waldyrious** [comment]
Unless @hamstar chimes in with his original rationale, I'd be inclined to follow the API's hierarchical model, both to maintain [consistency](https://en.wikipedia.org/wiki/Least_astonishment), and because I believe it makes more sense and can be handled more elegantly.

We can break compatibility if we release a new major version, and I would say it's warranted. We can make a minor release before that so that users of the current version can get the recent features and bugfixes, so that should not be a serious issue for end users, I believe.

**Comment by Xymph** [comment]
I suppose there's little point in waiting much longer for a :bell:. :smile:
I agree with your point about model consistency, but why would you accept breaking compatibility when a new `includeSubsections = false` parameter to `getSection` could allow old and new approaches to coexist?
Note: I'm okay either way, just trying to understand better.

**Comment by waldyrious** [comment]
>  why would you accept breaking compatibility when a new `includeSubsections = false` parameter to `getSection` could allow old and new approaches to coexist?

My comment was framed by your previous proposal (emphasis mine):

> as alternative to my proposed new method, `getText`'s section processing could be changed to match MW's model, but that would break compatibility in the `getSection` method. Unless it's done with an additional parameter that **defaults to the old behavior**

One obvious compromise is to include that parameter, but with the default set to match the upstream behavior (i.e. `includeSubsections` set to `false` by default). That way it would still create a compatibility break for unaltered code, but we'd support an easy way to upgrade, so in practice it wouldn't be as serious as removing the old behavior altogether. Would that be OK in your opinion?

**Comment by Xymph** [comment]
Crossing wires. :wink: If I understand you correctly, the new default behavior should match the API one, and therefore include subsections? Then the parameter's default would be `true` rather than `false` as above, if the name remains the same. And I can't think of an elegant name that inverts the meaning, especially not after the precending `includingHeading` parameter.

If that's correct, then I'm OK with this approach.

**Comment by waldyrious** [comment]
Sorry, my bad. I did mean the opposite, yes.

I agree the zeroth section's behavior may seem inconsistent, but since its section's heading is implicit, we could assume it's a virtual `<h2>` which would then qualm such concerns :P
