### ISSUE TITLE
php error ssl3

### ISSUE THREAD

**Issue by ivary** [hamstar/Wikimate#54]
He there,

first, thank you for the tool!

Since today i get the following error (apache error_log), yesterday my skript worked perfectly:

`PHP Fatal error:  Uncaught exception 'Requests_Exception' with message 'cURL error 35: error:1408D13A:SSL routines:SSL3_GET_KEY_EXCHANGE:unable to find ecdh parameters' in /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php:280\nStack trace:\n#0 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php(123): Requests_Transport_cURL->process_response(false, Array)\n#1 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(317): Requests_Transport_cURL->request('https://de.wiki...', Array, NULL, Array)\n#2 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(600): Requests::request('https://de.wiki...', Array, NULL, false, Array)\n#3 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(321): Requests::parse_response('HTTP/1.1 301 TL...', 'http://de.wikip...', Array, NULL, Array)\n#4 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(600): Requests::request('http://de.wikip...', Array,  in /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 280`

Does someone else gets that message?

**Comment by Xymph** [comment]
Hi,
Did you update Wikimate since your script still worked? If not, then the cause is likely elsewhere.
If yes, was the previous Wikimate version the one that still used Curl instead of Requests (before #22)?

I see a "HTTP/1.1 301" status in that log, indicating a permanent redirect is in place on the URL the script is trying to access. The URL also occurs both with (https://de.wiki...) and without SLL (http://de.wikip...) in the log. I'd analyze the connection request/response in more detail. [This post](http://stackoverflow.com/questions/34329398/using-curl-to-post-data-in-https-server-php/34329623) refers the same initial error and may provide direction.

**Comment by ivary** [comment]
I have started to use wikimate yesterday with the newest version. Worked perfect. Today and without changes it stopped working.

Just changed http-->https and now i get this error:

`PHP Fatal error:  Uncaught exception 'Requests_Exception' with message 'cURL error 35: error:1408D13A:SSL routines:SSL3_GET_KEY_EXCHANGE:unable to find ecdh parameters' in /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php:280\nStack trace:\n#0 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php(123): Requests_Transport_cURL->process_response(false, Array)\n#1 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests.php(317): Requests_Transport_cURL->request('https://de.wiki...', Array, NULL, Array)\n#2 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Session.php(202): Requests::request('https://de.wiki...', Array, NULL, 'GET', Array)\n#3 /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Session.php(129): Requests_Session->request('https://de.wiki...', Array, NULL, 'GET', Array)\n#4 /srv/www/htdocs/locations/new/Wikimate.php(206): Requests_Session->get('https://de.wiki...')\n#5 /srv/www/htdocs/locations/new in /srv/www/htdocs/locations/new/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 280`

**Comment by Xymph** [comment]
Well, this clearly isn't a problem in Wikimate, so I can only reiterate my last two sentences above. Perhaps something changed in the pertaining server's request/response handling.
Also, you could search the [Requests repo](https://github.com/rmccue/requests) if it's a known problem, or raise a new issue there.

**Comment by ivary** [comment]
ok thanks, maybe its a wikipedia problem...

**Comment by Xymph** [comment]
Ok, good luck. Issue closed.
