### ISSUE TITLE
Invalid page title echoes error

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#56]
When specifying an invalid page title (e.g. with a trailing ":") to WikiPage, it echoes an error message. It should use the error property instead.

Also, when getText loads such an invalid title, it should not continue processing it.

Various minor code and comment improvements will also be included in this PR.

**Comment by waldyrious** [comment]
Note that you can always make a PR consisting solely of minor fixes and improvements; they don't need to always fix a bug or implement a feature request :)

**Comment by Xymph** [comment]
True, in a way it got a little out of hand. It started with just a few queued-up tweaks, but as I worked through the file some more, further changes came up (some of which I missed during PRs long ago). At some point a separate issue would indeed have been a better approach, but it wasn't clear anymore where that point should be, so the thought didn't occur to me timely enough. :pensive:
