### ISSUE TITLE
New class WikiFile

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#58]
I need the ability to get information about files, and to upload them. I've started writing a new `WikiFile` class for this, still need to write the upload (and download, while I'm at it) methods. But I'd like to commit it after the changelog re-org and release tag are done, in order not to mingle branches/commits too much. So this is your cue, @waldyrious. :sunglasses:

**Comment by waldyrious** [comment]
👍 Give me until this weekend. I'll set some time aside to work on Wikimate.

**Comment by waldyrious** [comment]
Update: I've managed to clear up my github notifications backlog (which includes several projects). I don't think I'll have more time today to work on this, so expect the release update for tomorrow.

**Comment by waldyrious** [comment]
@Xymph after another weekend where I failed to put the release together, I guess I will have to face the facts: for the foreseeable future, I can't promise to be able to find the time to dedicate to this project on a regular basis. I'll remain around but I can't hold its progress hostage to my erratic (and fragmented) availability. Please move ahead with the release and other changes. I'll make sure to contribute what I can, when I can.

**Comment by Xymph** [comment]
No problem, I'm not in a hurry but will pick up the slack. :smiley: I'll work on the changelog issue (#60) next. And while writing the `WikiFile` class, sticking to the non-standard parenthesis formatting style kept feeling too awkward, so... I didn't anymore. :wink: Thus as a follow-up to an [earlier comment](https://github.com/hamstar/Wikimate/pull/37#issuecomment-251603674), I'd like to straighten that out in the existing classes now too. Objections?

So I'll do the commits and merges, but would still appreciate if you could review my changes before any merges. And your input on the $this-error issue (#59) would help too - it poses a minor API incompatibility, which I think is acceptable without doing a major version increment per semver, but I might be wrong.

After all that, creating the release can be done via the [Draft a new release](https://github.com/hamstar/Wikimate/releases) button, correct? I suppose I can manage that too then.

**Comment by waldyrious** [comment]
> No problem, I'm not in a hurry but will pick up the slack. 

Thanks for understanding, I appreciate it.

> I'd like to straighten that out in the existing classes now too. Objections?

None :) I take it that you're planning a dedicated PR for that?

> So I'll do the commits and merges, but would still appreciate if you could review my changes before any merges. 

Sure, I believe (seriously :P) I can do that.

> And your input on the error issue (#59) would help too

Of course, will do.

> After all that, creating the release can be done via the Draft a new release button, correct?

I am pretty sure, yes. I haven't done that myself though, so I'm not in a much better position than you in regards to this 😄

**Comment by Xymph** [comment]
> I take it that you're planning a dedicated PR for that?

It was just spacing, so I saved myself a little extra work by hitching it along in the changelog issue.

Thanks for your prompt :wink: feedback, then I'll take the release plunge after the other issues are done and merged.
