### ISSUE TITLE
Inconsistent value storing in $this->error

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#59]
When `$this->error` is filled from an API response, it's done in statements like this:
```
// Check for errors
if ( isset( $r['error'] ) ) {
    $this->error = $r; // Set the error if there was one
} else {
    $this->error = null; // Reset the error status
}
```
So `$this->error` becomes an array containing one key 'error' with an array as value, containing one or more key/value pairs with MediaWiki's errors. The interesting values are thus nested one level, to little purpose IMHO.

But other code, both existing and recently added by me, simply add an array element to `$this->error` directly, e.g. `$this->error['login']` and `$this->error['section']`.

While that's inconsistent, I'm not sure which way to make this consistent. Getting rid of the nesting level in API errors (i.e. using `$this->error = $r['error'];` above) might break existing code out there. Inserting the extra level at the other assignments seems a bit silly, too.

What do you think, @waldyrious?

**Comment by waldyrious** [comment]
I would go with flattening the structure. Resolving potential incompatibilities caused by that is likely to result in simpler downstream code, where the other option would have the opposite effect.

One general point about semver: I believe that until v1.0 is released, incompatible changes are allowed by changing only the minor version.

By the way, I would like to hear your thoughts about what we could consider 1.0 -- maybe [this checklist](https://github.com/mwclient/mwclient/issues/76) can provide some inspiration.

**Comment by Xymph** [comment]
> By the way, I would like to hear your thoughts about what we could consider 1.0 -- maybe this checklist can provide some inspiration.

Interesting list, good things to consider and strive for indeed. The first aspect that came to my mind wrt. to v1.0 is (reasonably) complete coverage of MediaWiki's API by Wikimate, but that's neither practical nor necessary. Impractical because that API is so large, and even with the upcoming WikiFile class this project is far from completely handling it. Unnecessary because -- like that checklist aims for -- maturity of what already _does_ exist in this project is at least as important as completeness, if not more so. Subsequent 2.0, 3.0, etc releases could then add major new chunks of API coverage.

That said, I'm not sure I'll be the one adding them. :smiley: I came to Wikimate because it was small and easy to understand (unlike some full-fledged frameworks out there), and provided just enough of what I needed for my application scripts. Then I needed file support too, so I wrote that, but at this time I don't anticipate requiring much more. Stuff like revisions, captchas, namespaces, users, categories, etc. etc. seem beyond my interest horizon. As is unit testing and many other things that can earn a project colorful buttons. :wink: 

For the near future, I'm planning to tag/release the current state as 0.11.0, and the WikiFile stuff could become 0.12.0. Beyond that, I'll probably wait and see.

What are your thoughts on a v1.0, then?

**Comment by waldyrious** [comment]
I agree that full coverage of the API would be too ambitious for a v1.0. Stabilizing what we have, establishing standards for the release process (semver, changelog format, explicit documentation of how to go about doing a release, etc.), documentation and code style, would qualify the project as having reached a stable level. Unit testing would be nice, but I have no experience writing them, much less in PHP. Maybe we could setup some linting with Travis, if you know of a good PHP linter / static code analysis tool we could use.

As for installation, is there a standard process for PHP tools? Maybe composer, an/or a repository like npm or pypi which we could register Wikimate in?

**Comment by Xymph** [comment]
While I have plenty PHP coding experience (including Zend Framework), I have not worked much or at all with all those things. And while I enjoy working on this project, I don't anticipate continue doing that much more for the sake of this project itself. Then I have too little time for my own stuff. :smiley: 
To some extent I hope that improving WikiPage and adding WikiFile soon will make Wikimate more attractive to other developers, and then maybe some with more experience in those areas can contribute in that direction.

**Comment by waldyrious** [comment]
Sure. Any improvement is positive step, and we don't have to put a 1.0 version out there. I just wanted to brainstorm what we would like a 1.0 version to look like.

**Comment by Xymph** [comment]
To make specific steps towards a v1.0, I propose to create specific issues. Meanwhile after a week of writing and using my various application scripts, no new issues came up. And one other user-submitted issue made it in just in time. :)

So now I've tagged the 0.11.0 release to clear the road for the WikiFile stuff, and am closing this here issue.
