### ISSUE TITLE
User agent is defined but not used

### ISSUE THREAD

**Issue by Xymph** [hamstar/Wikimate#62]
`$this->useragent` is defined but not passed to the Requests library, so HTTP requests use the library's agent string.

**Comment by Xymph** [comment]
Hmm, branched off the other branch instead of master. Well, it should be possible to merge it back after the other one is merged, right?

The fix was simple enough, I'm just wondering about the @todo above this method. Do you know what 'elsewhere' the version could be pulled from, if not the constant itself?

**Comment by waldyrious** [comment]
> Hmm, branched off the other branch instead of master. Well, it should be possible to merge it back after the other one is merged, right?

It's better to rebase. Fortunately just the other day I had to [write about this exact problem](https://github.com/tldr-pages/tldr/pull/1141#issuecomment-257587017), so that should help :)

> The fix was simple enough, I'm just wondering about the @todo above this method. Do you know what 'elsewhere' the version could be pulled from, if not the constant itself?

No idea. My best guess is that the `@todo` was added before the version was defined as a constant. Update: yeah, [that was the case](https://github.com/Xymph/Wikimate/commit/10966166fc3180abc1a2667a5eba014d24a34e78#diff-750ed7128b8f50be863c71c7254d6becR40).

**Comment by Xymph** [comment]
I tried it, but `git rebase --onto master 59-change-API-error-response 62-fix-useragent` returns an error:
```
First, rewinding head to replay your work on top of it...
Applying: Don't return null in constructor, it already returns the object
Applying: Ensured use of Wikimate user agent by Requests library (fixes #62)
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging CHANGELOG.md
CONFLICT (content): Merge conflict in CHANGELOG.md
Auto-merging Wikimate.php
Failed to merge in the changes.
Patch failed at 0002 Ensured use of Wikimate user agent by Requests library (fixes #62)
```
The tail end of CHANGELOG.md contains:
```
[...]
[#61]: https://github.com/hamstar/Wikimate/pull/61
<<<<<<< HEAD
=======
[#63]: https://github.com/hamstar/Wikimate/pull/63
[#64]: https://github.com/hamstar/Wikimate/pull/64
>>>>>>> Ensured use of Wikimate user agent by Requests library (fixes #62)
```
I understand why (entry #63 belongs to the other branch), but after I delete everything except the #64 line, should I run `git rebase --continue` as instructed? Will merging the other branch not result in another conflict because that's not expecting the #64 line?

Also, there's no PR on my Xymph/Wikimate fork for the #64 branch, so will the rebase/push eventually invoke one in hamstar/Wikimate ?

Thanks for your assistance. Once this is sorted out, I'll add a commit to delete that todo line, then.

**Comment by waldyrious** [comment]
According to https://github.com/hamstar/Wikimate/network, branches `59-change-API-error-response` and `62-fix-useragent` diverged on commit 614268c, right? To which branch does that commit semantically belong to?

* If it's part of `59-change-API-error-response`, as the graph coloring seems to indicate, then the rebase command should be `rebase --onto master 614268c 62-fix-useragent`.
* If on the other hand it does belong to `62-fix-useragent`, then no rebase will be needed for the 62 branch; only `59-change-API-error-response` needs to be rebased over `62-fix-useragent` (before the latter is merged into master).

So if the rebase command you did was not the appropriate one, I'd suggest aborting the rebase and starting a new one. Regardless, if commits occur, yes, you need to do `rebase --continue`, but don't forget to `git add` the conflicted files first, so it knows the conflicts have been resolved.

**Comment by Xymph** [comment]
What happened to cause the strange divert is that in `59-change-API-error-response`, I made one more tiny commit after branching `62-fix-useragent`, and then rebase/fixup-ed that with an earlier commit. Ugh.

Alright, I sorted out the conflict, ran `add CHANGELOG.md` and `rebase --continue` and pushed that. Now you can see the branch point 49eacbc in the updated graph and how it differs from the fixed-up one. I did not yet run another `rebase --onto`.

So commit 49eacbc would need to be taken out of `62-fix-useragent` completely, then its only intended commit remains and could be merged regardless of the other branch. Can that be done?

**Comment by waldyrious** [comment]
I'm not sure I'm following. The graph at https://github.com/hamstar/Wikimate/network shows 49eacbc as being the tip of `master`, and not included in `62-fix-useragent` at all. Am I missing something?

**Comment by Xymph** [comment]
Oi, being referencing parents instead of commits. I meant e3055a3 :hushed: That's the one that would need to be removed from `62-fix-useragent` entirely.

**Comment by waldyrious** [comment]
Yep, that should do it :)

**Comment by Xymph** [comment]
Ok thanks, all that was rather... educational. :roll_eyes: I'll have to be more careful where I branch from.

**Comment by waldyrious** [comment]
Most of the time it's nice learning about git's internals to improve our mental model and our capacity to reason about the graph and how to modify it. Unfortunately, that often includes learning about the quirks of git's CLI, which is useful in practice but not as satisfying intellectually. Good thing it keeps getting better release after release, albeit a little slower than I'd wish.
