### ISSUE TITLE
Bad handling of login error

### ISSUE THREAD

**Issue by Hexasoft** [hamstar/Wikimate#66]
Hello,
while testing the code I made a mistake: I used HTTP URL rather than HTTPS URL for the $domain parameter for login() function.
It lead to an HTML error from api.php, and so a NULL $response->body, which then generates PHP warnings at line 96 in Wikimate.php.
I just changed the line to prevent that:
if ($loginResult->login->result == 'NeedToken') {
becomes
if (isset($loginResult) and isset($loginResult->login) and ($loginResult->login->result == 'NeedToken')) {

It is useful in this case but may also handle other cases (such as servers problem).

Regards

**Comment by Xymph** [comment]
Thanks for the report, the fix has been committed and merged.
