### ISSUE TITLE
Feature request: custom requests

### ISSUE THREAD

**Issue by Oreolek** [hamstar/Wikimate#86]
Is there a way to call a custom **action**, like "ask" (Semantic MW)

**Comment by Xymph** [comment]
I'm not sure what that means; can you elaborate, provide an example?

At the outset, I can just say that Wikimate supports only a small portion of the [MediaWiki API](https://www.mediawiki.org/wiki/API:Main_page), and thus no features specific to other wiki APIs.

**Comment by Xymph** [comment]
Closed due to lack of a follow-up.
