### ISSUE TITLE
Any way to preserve login session

### ISSUE THREAD

**Issue by gyan111** [hamstar/Wikimate#91]
It seems we have to login to for each operation. Is there anyway to retain the session and do operations after login once.

**Comment by gyan111** [comment]
What I am saying is:
I am performing this 
`$wiki->login($username, $password`
In the starting and it works for all operations.

Only concern is if I call another function can I preserve the logged in session?

**Comment by Xymph** [comment]
$wiki remains usable throughout the _script_ it was initialized in. Not sure what your "another function" means in this context.
I suppose you could serialize/unserialize $wiki to keep using the $wiki object with its session data in another script.

**Comment by gyan111** [comment]
The context is:
#1 I make a call to just login. If login successful which will show them another page.
#2 On the next page I want to make another call to scrip to make a modification.

Is that possible? 

Can I save  the $wiki in session and re use it?

**Comment by gyan111** [comment]
Thank You for replying.

I have used wikimate here.

https://jsahu.me/wiki/mass-message

I want to show another page after login to users and do other operations.

**Comment by Xymph** [comment]
Ok, now I understand the context. My previous suggestion stands, some useful search results are [here](https://stackoverflow.com/a/5758782) and [here](https://davidwalsh.name/php-serialize-unserialize-issues). Developing & testing this would be beyond the scope of Wikimate, so I'm closing this issue. Good luck.
