### ISSUE TITLE
Update documentation to adding/editing a page

### ISSUE THREAD

**Issue by tacman** [hamstar/Wikimate#94]
In the examples.php, the "Sausages" page is fetched.  

https://github.com/hamstar/Wikimate/blob/master/examples.php

```php
        echo "Fetching 'Sausages'...\n";
        $page = $wiki->getPage('Sausages');

// check if the page exists or not
        if (!$page->exists() ) {
            echo "'Sausages' doesn't exist.\n";
            /** @todo: add content and save page */
        }

```

I'm not sure how to update and save a page, would love to see a few lines of code that added that page and some content.

**Comment by Xymph** [comment]
Is [this](https://github.com/Xymph/Wikimate/blob/95-expand-examples/examples.php) sufficient?

**Comment by tacman** [comment]
Terrific, thanks!

I had thought there were two steps, setting the page content and then executing the API call (like a flush() when working with an ORM), so I didn't realize it was so simple.  Thanks.

**Comment by Xymph** [comment]
Okay, PR #95 merged.
