### ISSUE TITLE
Deprecated CSRF token parameters

### ISSUE THREAD

**Issue by albertoleoncio** [hamstar/Wikimate#99]
- https://lists.wikimedia.org/hyperkitty/list/wikitech-l@lists.wikimedia.org/thread/IMP43BNCI32C524O5YCUWMQYP4WVBQ2B/
- https://github.com/hamstar/Wikimate/blob/3c8833abd5cfed36beb0e04d024727bdfc7baea9/Wikimate.php#L537

**Comment by Xymph** [comment]
PR #100 addresses this. Would you be able to review it, @albertoleoncio ?

**Comment by albertoleoncio** [comment]
@Xymph Sorry, but it's a little beyond my PHP skills. Is there anyone else?

**Comment by Xymph** [comment]
@albertoleoncio Yes, see the PR.
